### ISSUE TITLE
Replace the dependency on (deprecated) stahnma/epel with puppet/epel

### ISSUE THREAD

**Issue by jcbollinger** [voxpupuli/puppet-virtualbox#111]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: all
- Ruby: all
- Distribution: n/a
- Module version: 4.0.1

## How to reproduce (e.g Puppet code you use)

n/a

## What are you seeing

The module expresses a dependency on module stahnma/epel, which has been handed over by its author to Voxpupuli.  stahnma/epel is accordingly deprecated, but puppet/virtualbox still depends on it.

## What behaviour did you expect instead

puppet/virtualbox should depend on puppet/epel instead of stahnma/epel.

## Output log

n/a

## Any additional information you'd like to impart

n/a

**Comment by ekohl** [comment]
This was fixed in d6b4c224c03a88aea43793dffe216f12419877b4.
