### ISSUE TITLE
Warning message regarding unsupported architecture

### ISSUE THREAD

**Issue by meskaya** [voxpupuli/puppet-virtualbox#80]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.4.0-2ubuntu3
- Ruby: 1:2.5.1
- Distribution: Ubuntu 18.04.1
- Module version: 2.2.1

## How to reproduce (e.g Puppet code you use)
  class { '::virtualbox':                                                                                                                                                              
    manage_kernel  => false,                                                                                                                                                                                
    manage_package => false,                                                                                                                                                                                
  }    

## What are you seeing
> sudo apt update
N: Skipping acquire of configured file 'contrib/binary-i386/Packages' as repository 'http://download.virtualbox.org/virtualbox/debian bionic InRelease' doesn't support architecture 'i386'

## What behaviour did you expect instead
No warning message regarding VirtualBox repository

## Any additional information you'd like to impart

I was thinking maybe adding the node architecture to the apt::source to remove the message about i386 arch not supported.

# == Class: virtualbox::install

        apt::source { 'virtualbox':
          architecture => $::virtualbox::params::architecture,
          location     => 'http://download.virtualbox.org/virtualbox/debian',
          release      => $::lsbdistcodename,
          repos        => $apt_repos,
          require      => Apt::Key[ $apt_key_thumb ],
        }

# == Class virtualbox::params

  $architecture    = $facts['architecture']

==>
/etc/apt/sources.list.d/virtualbox.list

deb [arch=amd64]  http://download.virtualbox.org/virtualbox/debian bionic contrib

Cheers,
Franck

**Comment by meskaya** [comment]
Hi @Dan33l,
No I am using an x86_64 node (Ubuntu 18.04.1)

**Comment by meskaya** [comment]
It's maybe the opportunity to add support of Ubuntu 18.04 ;)

**Comment by Dan33l** [comment]
You are welcome if you want to provide a PR.

But we are with an issue about acceptance tests in this module.
https://github.com/voxpupuli/puppet-virtualbox/pull/71#issuecomment-412841288

And our acceptance tests use docker but for this module it is not possible due to load of kernel modules.

**Comment by meskaya** [comment]
Hi @Dan33l,
It's the first time I am creating a pull request :)
You are asking for a failing test but I am not fixing something failing but just adding the architecture to the repository definition.

So :

Fork it --> DONE
Create a feature branch --> DONE (https://github.com/meskaya/puppet-virtualbox/tree/architecture)
Write a failing test --> it's not failing it's just the repo definition that needs architecture on Ubuntu 18.04
Write the code to make that test pass --> code is part of the new branch
Refactor the code --> DONE
Submit a pull request --> will do it as soon as you tell me it's ok or if I have to do something first

**Comment by Dan33l** [comment]
Hi @meskaya a travel start with a first step. Let's move forward together

You can find guidance about contributing here in [CONTRIBUTING.md](https://github.com/voxpupuli/puppet-virtualbox/blob/master/.github/CONTRIBUTING.md)

If you wish, you can also join Voxpupuli members on channel #voxpupuli by [IRC](https://webchat.freenode.net/) or Slack. It should be more interactive than here.

It is difficult to find what is changed from our master branch without pull request. So, please submit the pull request and we will be able to talk about modifications.
